apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: my-hello-world
image: rancher/k3s:v1.25.6-k3s1
servers: 1
agents: 1
ports:
  - port: 80:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer