apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
  labels:
    app: {{ include "hello-world-chart.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "hello-world-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-world-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository}}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
