apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world-chart.name" . }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "hello-world-chart.name" . }}
            port:
              number: 80
